package deck

import (
	"fmt"
	"strings"

	"github.com/henry-clone/internal/domain"
)

func (b *Builder) assembleHTML(deal *domain.Deal, sections []domain.Section) string {
	brand := deal.Brand
	if brand.ID == "" {
		brand = domain.DefaultBrand()
	}

	var body strings.Builder

	if brand.LogoURL != "" {
		body.WriteString(fmt.Sprintf(`<header class="deck-header">
			<img src="%s" alt="%s" class="brand-logo" />
		</header>`, brand.LogoURL, brand.Name))
	}

	for _, s := range sections {
		body.WriteString(fmt.Sprintf(`<section class="deck-section %s">
			<div class="section-label">%s</div>
			<div class="section-content">%s</div>
		</section>`, s.Type, s.Title, s.Content))
		body.WriteString("\n")
	}

	// Footer
	body.WriteString(`<footer class="deck-footer">
		<div class="footer-inner">
			<span>Confidential Offering Memorandum</span>
			<span class="footer-brand">Generated by Henry Clone</span>
		</div>
	</footer>`)

	css := b.brandedCSS(brand)

	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>%s — Deal Deck</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Playfair+Display:wght@400;600;700&display=swap" rel="stylesheet">
<style>
%s
</style>
</head>
<body>
<div class="deck">
%s
</div>
</body>
</html>`, deal.Property.Name, css, body.String())
}

func (b *Builder) brandedCSS(brand domain.Brand) string {
	return fmt.Sprintf(`
* { margin: 0; padding: 0; box-sizing: border-box; }

:root {
	--primary: %s;
	--secondary: %s;
	--accent: %s;
}

body {
	font-family: 'Inter', -apple-system, sans-serif;
	background: #e8e8e8;
	color: #1a1a1a;
	line-height: 1.7;
	-webkit-font-smoothing: antialiased;
}

.deck {
	max-width: 1000px;
	margin: 0 auto;
	background: white;
	box-shadow: 0 4px 40px rgba(0,0,0,0.12);
}

/* ── Header ── */
.deck-header {
	padding: 28px 80px;
	border-bottom: 3px solid var(--primary);
	background: #fafafa;
}
.brand-logo { height: 36px; width: auto; }

/* ── Sections ── */
.deck-section {
	padding: 64px 80px;
	border-bottom: 1px solid #f0f0f0;
	page-break-inside: avoid;
	position: relative;
}

.deck-section::before {
	content: '';
	position: absolute;
	left: 0;
	top: 0;
	bottom: 0;
	width: 4px;
	background: transparent;
}

.section-label {
	font-family: 'Inter', sans-serif;
	font-size: 11px;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 3px;
	color: var(--accent);
	margin-bottom: 28px;
	padding-bottom: 12px;
	border-bottom: 2px solid #f0f0f0;
}

/* ── Cover ── */
.cover {
	padding: 100px 80px;
	background: linear-gradient(135deg, #0a0a0a 0%%, #1a1a2e 50%%, #16213e 100%%);
	text-align: left;
	border-bottom: none;
	min-height: 500px;
	display: flex;
	align-items: flex-end;
}
.cover .section-label { display: none; }
.cover .section-content { width: 100%%; }

.cover-inner {
	border-left: 4px solid var(--accent);
	padding-left: 32px;
}

.cover-inner h1 {
	font-family: 'Playfair Display', Georgia, serif;
	font-size: 48px;
	font-weight: 700;
	color: white;
	line-height: 1.15;
	margin-bottom: 16px;
	letter-spacing: -0.5px;
}

.cover-inner .address {
	font-size: 18px;
	color: rgba(255,255,255,0.7);
	font-weight: 300;
	margin-bottom: 6px;
}

.cover-inner .asset-class {
	font-size: 13px;
	text-transform: uppercase;
	letter-spacing: 2px;
	color: var(--accent);
	font-weight: 600;
}

.cover-inner .cover-divider {
	width: 60px;
	height: 2px;
	background: var(--accent);
	margin: 20px 0;
}

.cover-inner .cover-tagline {
	font-size: 15px;
	color: rgba(255,255,255,0.5);
	font-weight: 300;
	font-style: italic;
}

/* ── Content ── */
.section-content {
	font-size: 15.5px;
	color: #2d2d2d;
	line-height: 1.8;
}
.section-content p { margin-bottom: 18px; }

/* ── Tables ── */
table {
	width: 100%%;
	border-collapse: collapse;
	margin: 20px 0;
	font-size: 14px;
}

th, td {
	padding: 12px 18px;
	text-align: left;
	border-bottom: 1px solid #f0f0f0;
}

th {
	font-weight: 700;
	color: var(--primary);
	background: #f8f9fa;
	text-transform: uppercase;
	font-size: 10.5px;
	letter-spacing: 1.5px;
	border-bottom: 2px solid #e0e0e0;
}

td:last-child, th:last-child { text-align: right; }

tbody tr:hover { background: #fafbfc; }

.subtotal td {
	font-weight: 700;
	border-top: 2px solid #ddd;
	background: #f8f9fa;
}

.total td {
	font-weight: 800;
	font-size: 16px;
	border-top: 3px solid var(--primary);
	padding-top: 18px;
	color: var(--primary);
}

/* ── Metrics ── */
.metrics {
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
	gap: 24px;
	margin-top: 36px;
	padding-top: 28px;
	border-top: 2px solid #f0f0f0;
}

.metric {
	background: #f8f9fa;
	border-radius: 12px;
	padding: 20px 24px;
	border: 1px solid #eee;
}

.metric .label {
	font-size: 10px;
	text-transform: uppercase;
	letter-spacing: 1.5px;
	color: #888;
	font-weight: 600;
	margin-bottom: 6px;
}

.metric .value {
	font-size: 32px;
	font-weight: 800;
	color: var(--primary);
	letter-spacing: -1px;
	line-height: 1.1;
}

/* ── Rent Roll ── */
.rent-roll table { font-size: 13px; }
.vacant { color: #e74c3c; font-weight: 600; }

/* ── Comps ── */
.comps table { font-size: 13px; }
.comps tfoot td { font-weight: 700; background: #f8f9fa; }

/* ── Demographics ── */
.demographics table td:first-child { font-weight: 500; color: #555; }

/* ── Photos ── */
.photo-gallery {
	display: grid;
	grid-template-columns: repeat(2, 1fr);
	gap: 16px;
}
.photo-gallery img { border-radius: 12px; }

/* ── Location Map ── */
.location-map img { border-radius: 12px; }
.location-details { margin-top: 16px; font-size: 14px; color: #555; }

/* ── Valuation ── */
.valuation .total td { color: var(--accent); }

/* ── Financials ── */
.financials table { margin-bottom: 0; }

/* ── Footer ── */
.deck-footer {
	padding: 32px 80px;
	background: #fafafa;
	border-top: 1px solid #eee;
}
.footer-inner {
	display: flex;
	justify-content: space-between;
	font-size: 11px;
	color: #aaa;
	text-transform: uppercase;
	letter-spacing: 1px;
}
.footer-brand { font-weight: 600; }

/* ── Print ── */
@media print {
	body { background: white; }
	.deck { box-shadow: none; }
	.deck-section { padding: 48px 60px; }
	.cover { min-height: 600px; }
	tbody tr:hover { background: transparent; }
}

a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
`,
		brand.PrimaryColor,
		brand.SecondaryColor,
		brand.AccentColor,
	)
}
